version: 2.1
orbs:
  maven: circleci/maven@1.3.0
executors:
  j8:
    docker:
      - image: 'cimg/openjdk:8.0'
  j11:
    docker:
      - image: 'cimg/openjdk:11.0'
workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test
          matrix:
            parameters:
              executor:
                - j8
                - j11
